### ISSUE TITLE
SegFault on exit

### ISSUE THREAD

**Issue by Type1J** [makepad/makepad#187]
I get `Segmentation fault (core dumped)` on exit of any of the examples. (Nobara Linux 36, x86_64)

**Comment by oswald2** [comment]
Same here on Ubuntu 22.04. Valgrind shows the following:


> ==11082== Process terminating with default action of signal 11 (SIGSEGV)
> ==11082==  Access not within mapped region at address 0xF8
> ==11082==    at 0x48B47BD: XCloseDisplay (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
> ==11082==    by 0x24172A: makepad_platform::os::linux::x11::xlib_app::XlibApp::do_callback (in /home/oswald/Projects/Rust/makepad/target/release/makepad-example-simple)
> ==11082==    by 0x2403D4: makepad_platform::os::linux::x11::xlib_app::XlibApp::event_loop_poll (in /home/oswald/Projects/Rust/makepad/target/release/makepad-example-simple)
> ==11082==    by 0x2412B8: makepad_platform::os::linux::x11::xlib_app::XlibApp::event_loop (in /home/oswald/Projects/Rust/makepad/target/release/makepad-example-simple)
> ==11082==    by 0x229FDF: makepad_platform::os::linux::x11::linux_x11::<impl makepad_platform::cx::Cx>::event_loop (in /home/oswald/Projects/Rust/makepad/target/release/makepad-example-simple)
> ==11082==    by 0x1474F2: std::sys_common::backtrace::__rust_begin_short_backtrace (in /home/oswald/Projects/Rust/makepad/target/release/makepad-example-simple)
> ==11082==    by 0x147508: std::rt::lang_start::{{closure}} (in /home/oswald/Projects/Rust/makepad/target/release/makepad-example-simple)
> ==11082==    by 0x33767A: std::rt::lang_start_internal (function.rs:284)
> ==11082==    by 0x147564: main (in /home/oswald/Projects/Rust/makepad/target/release/makepad-example-simple)


So the crash happens in the X library. Maybe a problem in the binding.

**Comment by Type1J** [comment]
By the way, I'm on Wayland in my scenerio, so if most people are not seeing the issue, it could be the X to Wayland translation, but I'm not sure what @oswald2 is using.

**Comment by oswald2** [comment]
Actually, I thought I am also on Wayland, but on re-checking I noticed Ubuntu Studio 22.04 is still on X11.

**Comment by obsoleszenz** [comment]
Same here on kde plasma (wayland).
gdb backtrace:
```
Thread 1 "makepad-example" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e85c00 in XCloseIM (im=0x555555dff570) at xlibi18n/IMWrap.c:134
134         s = (im->methods->close) (im);                                                                                                                               
(gdb) bt
#0  0x00007ffff7e85c00 in XCloseIM (im=0x555555dff570) at xlibi18n/IMWrap.c:134
#1  0x000055555599b5f2 in makepad_platform::os::linux::x11::xlib_app::XlibApp::terminate_event_loop (self=0x555555cf0f90) at platform/src/os/linux/x11/xlib_app.rs:595
#2  0x000055555599b4b0 in makepad_platform::os::linux::x11::xlib_app::XlibApp::do_callback (self=0x555555cf0f90, event=...) at platform/src/os/linux/x11/xlib_app.rs:587
#3  0x0000555555a1ec1c in makepad_platform::os::linux::x11::xlib_window::XlibWindow::do_callback (self=0x555555f840c0, event=...)
    at platform/src/os/linux/x11/xlib_window.rs:391
#4  0x000055555599a9dc in makepad_platform::os::linux::x11::xlib_app::XlibApp::event_loop_poll (self=0x555555cf0f90) at platform/src/os/linux/x11/xlib_app.rs:207
#5  0x000055555599b27c in makepad_platform::os::linux::x11::xlib_app::XlibApp::event_loop (self=0x555555cf0f90) at platform/src/os/linux/x11/xlib_app.rs:576
#6  0x00005555559ee56d in makepad_platform::cx::Cx::event_loop (cx=...) at platform/src/os/linux/x11/linux_x11.rs:67
#7  0x000055555571872c in makepad_example_simple::app::app_main () at platform/src/app_main.rs:26
#8  0x0000555555716da7 in makepad_example_simple::main () at examples/simple/src/main.rs:5
```

EDIT: Interesting that there's some x11 /xorg stuff mentioned. Maybe makepad doesn't support wayland yet?

**Comment by yulnr** [comment]
Closing this since native wayland support has been added (although not fully ready yet) and the code related to this panic has been reworked since reported.

You can keep track of this here: https://github.com/makepad/makepad/issues/476
Or report a new issue if you find this to still be a problem (or similar)
