### ISSUE TITLE
It seems to be a text encoding issue?

### ISSUE THREAD

**Issue by aprchen** [makepad/makepad#283]
➜  makepad git:(master) ✗ cargo run -p makepad-studio --release            
    Finished release [optimized] target(s) in 0.30s
     Running `target/release/makepad-studio`
studio/src/file_system/file_client_desktop.rs:122:9 - Server listening on 127.0.0.1:54141
studio/src/build_manager/build_manager.rs:413:9 - Http server at http://127.0.0.1:8001/ for wasm examples and mobile
thread 'main' panicked at 'byte index 63 is not a char boundary; it is inside '—' (bytes 61..64) of `            label.set_text_and_redraw(cx,&format!("Counter——: {}", self.counter));`', code_editor/src/text.rs:64:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', studio/src/file_system/file_client_desktop.rs:213:47

**Comment by kevinaboos** [comment]
This has been fixed recently; please try it again!
