### ISSUE TITLE
usability issues

### ISSUE THREAD

**Issue by univerz** [makepad/makepad#294]
i've been playing with makepad today and found a few problems/bugs. the easiest way to investigate is to apply this patch to the news_feed example (adds TextInput to the top).

(`git apply --whitespace=fix d.diff`)
```diff
diff --git a/examples/news_feed/src/app.rs b/examples/news_feed/src/app.rs
index 2ddf90851..03c75dbc4 100644
--- a/examples/news_feed/src/app.rs
+++ b/examples/news_feed/src/app.rs
@@ -114,17 +114,16 @@ live_design!{
         width: Fill,
         height: 70
         flow: Right,
-        padding: 10.0,
-        spacing: 10.0
         draw_bg: {color: (COLOR_OVERLAY_BG), inset: vec4(-0.5, -0.5, -1.0, 0.0), radius: vec2(0.5, 4.5)}
 
-        <Logo> {
-            height: Fit,
+        search = <TextInput> {
             width: Fill,
             margin: {top: 0.0}
-            icon_walk: {width: Fit, height: 27.0}
-        }
+            height: Fit,
 
+            empty_message: "search"
+            draw_bg: { color: #xddd8cc }
+         }
     }
 
     Menu = <RoundedYView> {
```

* ~linux(plasma-wayland)~ #340  and android (14): no copy&paste to/from app
* ~linux: there is something special going on in the upper part of the window - if the TextInput is placed there, makepad has a problem switching the cursor icon - it works only if approached from bottom and works mostly over bottom padding (it switches to dragging the window if clicked on the upper part)~ #341 
* android
	* TextInput::wrap::Line allows to input newlines (works ok on linux) ~& they are hard to select/delete from the input (tested begin, middle and end positions)~
	* moving cursor using sliding over spacebar doesn't work
	* selecting text is hard to use without "enlarged" & movable start/end
	* missing copy/paste
	* makepad doesn't use more screen space compared to other apps, but the android top bar (with time and icons) is not visible
	* ~`developer options > show refresh rate` stays at 120 compared to dropping to 10 when idle (firefox, twitter)~
	* ~[unused screen space](https://github.com/makepad/makepad/issues/294#issuecomment-1763574877)~
	* when (kinetic) scrolling, it sometimes starts scrolling too fast at the end of the thumb movement. this post about [kinetic scrolling](https://xi.zulipchat.com/#narrow/stream/351333-glazier/topic/Kinetic.20and.20line.2Fpage.20scrolling/near/387346577) may help.
* wasm
	* ~selecting text with mouse doesn't work when letter `j` is inserted (this was probably part of the problem on android; i suspect the underlying problem is rounding / fragile newline detection on hidpi)~ #420 
	* keyboard doesn't open on mobile browser (egui can do it)
	* copy/paste on mobile browser (not sure if it is possible)

* ~minor things (which i can probably fix myself)~
	* ~TextInput~
		* ~shows cursor when not focused~
		* ~in this example the cursor is too tall (and in my other code it is the opposite - it is a little bit too small)~
		* ~cursor can move over the top of the input on android when all text except newlines is deleted~

* bonus points
	* autocomplete login, save/load password on android
	* select & copy text from labels

**Comment by univerz** [comment]
now i have trouble reproducing the problem with the letter `j` on wasm, but there is definitely some problem with the `ff` (ligature) - when moving the cursor with the keyboard arrows, it behaves as a single symbol and creates a selection shift in the words that follow (wasm, linux, android).

now i can reproduce selection problem on android with this diff on top (clearly it depends on some small differences, i can tap into words with these sizes in my project, but i changed other things too)
```diff
diff --git a/examples/news_feed/src/app.rs b/examples/news_feed/src/app.rs
index 5ee14acb..a417f00d 100644
--- a/examples/news_feed/src/app.rs
+++ b/examples/news_feed/src/app.rs
@@ -17,8 +17,8 @@ live_design!{
     ICO_USER = dep("crate://self/resources/icon_user.svg")
     ICO_ADD = dep("crate://self/resources/icon_add.svg")
     
-    FONT_SIZE_SUB = 9.5
-    FONT_SIZE_P = 12.5
+    FONT_SIZE_SUB = 11
+    FONT_SIZE_P = 14
     
     TEXT_SUB = {
         font_size: (FONT_SIZE_SUB),
@@ -301,7 +301,6 @@ live_design!{
     
     App = {{App}} {
         ui: <Window> {
-            window: {inner_size: vec2(428, 926), dpi_override: 2},
             show_bg: true
```

when i enter 2 words `aaaa bbbb` it's not possible to place cursor on second word by tapping it. `pr` instead of space produces the same result (`aaaaprbbbb`) - can't place cursor to `bbbb` part, `aaaabbbb` is ok.

**Comment by univerz** [comment]
with `window.dpi_override` removed i noticed that there is unused (gray) space on the right and bottom. with `window: {dpi override: 4},` there is some space at the bottom => it's a bit of a coincidence that `dpi override:2` looks almost normal on my device (pixel 7pro; now that I know where to look, I see 1-2 pixels).

![Screenshot_20231016-025437](https://github.com/makepad/makepad/assets/1024741/25066bfb-a83f-404a-96e5-305490c7a1f5)

![Screenshot_20231016-025246](https://github.com/makepad/makepad/assets/1024741/3f71867d-95a0-42c9-91a5-bc72b7de949c)

**Comment by univerz** [comment]
* `ff` - we need this https://harfbuzz.github.io/clusters.html (@eddyb ?)
* `aaa bbb` / `aaaprbbb` - i can reproduce it with first diff and wasm on firefox with max zoom (500%, 400% is not enough) which should be easier to debug than running it on device. (i don't understand the code yet, but there are some f64 -> f32 -> f64 conversions around rect_pos/size/advance)

**Comment by makepaddev** [comment]
Thanks for your reports, yea we have a lot of papercuts. Btw one of the problems with textinput with ligatures is that it doesnt work at all rn. This is because say fi becomes a special character so the cursor position is off. The rest you found we'll also have to chase.

**Comment by univerz** [comment]
> textinput with ligatures is that it doesnt work at all rn

it would be great to resolve this in a way that allows rich text on individual characters later.

**Comment by makepaddev** [comment]
Right now i don't even have any ideas how to fix this. We need to separate the geometry rendering of the text from trying to figure out where the cursor needs to go. Since i get 'a single piece of geometry' out i have no idea how to put a cursor inbetween a ligature since i'd be like putting it in the middle of an X ...

**Comment by univerz** [comment]
have you considered using cosmic-text? code looks nice and it's possible to place cursor in the middle of `ff` (but using different color for each f fails in rich-text example).

**Comment by univerz** [comment]
> * linux: there is something special going on in the upper part of the window - if the TextInput is placed there, makepad has a problem switching the cursor icon - it works only if approached from bottom and works mostly over bottom padding (it switches to dragging the window if clicked on the upper part)

problem with clicking into/focusing the input is caused by [this line](https://github.com/makepad/makepad/blob/rik/platform/src/os/linux/x11/xlib_app.rs#L314). the problem that the text icon only appears when hovering over the bottom padding persists.

**Comment by univerz** [comment]
> * linux(plasma-wayland) and android (14): no copy&paste to/from app

problem on linux is caused by [`\n` instead of `\0`](https://github.com/makepad/makepad/blob/rik/platform/src/os/linux/x11/xlib_app.rs#L871). btw @makepaddev - could ctrl/shift-insert be added alongside ctrl-c/v?

**Comment by univerz** [comment]
> > * linux: there is something special going on in the upper part of the window - if the TextInput is placed there, makepad has a problem switching the cursor icon - it works only if approached from bottom and works mostly over bottom padding (it switches to dragging the window if clicked on the upper part)
> 
> problem with clicking into/focusing the input is caused by [this line](https://github.com/makepad/makepad/blob/rik/platform/src/os/linux/x11/xlib_app.rs#L314). the problem that the text icon only appears when hovering over the bottom padding persists.

the problem starts [here](https://github.com/makepad/makepad/commit/8c7f532a6c6a92ff35bf089255d4bcbc14192cfe#diff-6a3ddaee11439afeec3f9e7a0b7be0b2e693ba3cb422f5e7dd334314d2db261eR157). `SysMenu` is windows only and is not used, so maybe it could be removed from the api and then guard the whole thing from [r151](https://github.com/makepad/makepad/commit/8c7f532a6c6a92ff35bf089255d4bcbc14192cfe#diff-6a3ddaee11439afeec3f9e7a0b7be0b2e693ba3cb422f5e7dd334314d2db261eR151) with ~```if (self.view(id!(caption_bar)).is_visible())```?

**Comment by univerz** [comment]
@eddybruel i confirm your recent work fixes ligature issues, but:

1. there is one more error with multiline text input. (rik branch with patch from the first post)

* on linux> enter `a` shift-enter `a`, place cursor after first `a`, backspace
```
thread 'main' panicked at draw/src/shader/draw_text.rs:632:59:
called `Option::unwrap()` on a `None` value
```

* on android> `a` enter soft key (keyboard closes), click to input, `a`, click on first line, backspace
```
09-02 01:52:27.781 27393 27424 D Makepad : platform/src/os/linux/android/android.rs:510:12 - Custom panic hook: panicked at draw/src/shader/draw_text.rs:632:59:
09-02 01:52:27.781 27393 27424 D Makepad : called `Option::unwrap()` on a `None` value
09-02 01:52:27.795 27393 27393 D Makepad : platform/src/os/linux/android/android.rs:510:12 - Custom panic hook: panicked at platform/src/os/linux/android/android_jni.rs:118:44:
09-02 01:52:27.795 27393 27393 D Makepad : called `Result::unwrap()` on an `Err` value: SendError { .. }
09-02 01:52:27.797 27393 27393 D Makepad : platform/src/os/linux/android/android.rs:510:12 - Custom panic hook: panicked at core/src/panicking.rs:221:5:
09-02 01:52:27.797 27393 27393 D Makepad : panic in a function that cannot unwind
```

2. degraded text rendering (linux, rotated 4k @ 31.5" lcd) - on the left is commit 5e71879 (rik's merge to master right before your work on text rendering + changed text to match rik branch), on the right is current rik branch. notice the size of `w` & `y` compared to other letters in `How are you` & `r` in `User`.
![Screenshot_20240902_014115](https://github.com/user-attachments/assets/a132c53e-b4f9-4fe2-8d57-ed9deb46055c)
 
(note that quality of rendering on the left is degraded too compared to pre-sdf state)

**Comment by eddybruel** [comment]
Hi @univerz,

I had trouble reproducing your first issue, but I think I know what caused it: the panic happens in the picking algorithm, which tries to map a position on the screen to an offset in the text. It does this by keeping track of the end offset of the previous grapheme, However, this is initially set to None, and does not get set until the first non-newline text is encountered. Therefore, if the first two lines are empty, when the second line is encountered, it tries to obtain the end offset of the previous grapheme, which is still None, causing the panic.

To fix this, I've changed prev_grapheme_end from an Option<usize>, and changed its initial value from None to 0. Moreover, whenever we encounter a newline, it should be incremented by 1 (this assumes that every newline character is exactly 1 byte long, which is not strictly true, due to CR + LF pairs, but should work well enough for now). This seems to fix all the issues with moving the cursor when there are multiple empty lines present.

Since I could not reproduce your exact issue, can you please confirm that this also fixed the panic on your system? (I pushed the fix to the rik branch).

**Comment by univerz** [comment]
> can you please confirm that this also fixed the panic on your system? (I pushed the fix to the rik branch).

works great, thank you :)

> 959a6c3 Fix bug in sdf padding

this one helped too

![Screenshot_20240904_031250](https://github.com/user-attachments/assets/10a8453b-d763-44eb-b9c5-0eb434e9b1ff)


> I had trouble reproducing your first issue

situation looked like this before backspace endgame
![Screenshot_20240904_024906](https://github.com/user-attachments/assets/a562f8e2-d297-4f9a-a222-7beee19bf5b0)
