### ISSUE TITLE
studio panic

### ISSUE THREAD

**Issue by kontsaki** [makepad/makepad#304]
Hello, clicking on any example on the left of the studio UI results in a panic

```
hread 'main' panicked at platform/src/os/linux/x11/opengl_x11.rs:103:41:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at studio/core/src/file_system/file_client_desktop.rs:223:47:
called `Result::unwrap()` on an `Err` value: RecvError
```

running Fedora Rawhide Gnome Wayland
makepad from current master

**Comment by makepaddev** [comment]
Looks like cxtexture.os.gl_texture.unwrap() as egl_sys::EGLClientBuffer, that thing is none.

**Comment by makepaddev** [comment]
So either linux is just broken or its only for your system

**Comment by camperking** [comment]
Same problem here on linux mint with cinnamon desktop. I do have a second gpu, maybe this causes the problem?
