### ISSUE TITLE
Panic on windows

### ISSUE THREAD

**Issue by SpirosMakris** [makepad/makepad#39]
Hello,

tried to run makepad on a Windows 10 machine. Compilation succeeds and the makepad window briefly pops up before panicking. Attaching verbose stack trace below.

Could this be a problem with the port (I believe its hardcoded to 2001) being already bound to something?

Also, thank you for making makepad. I believe it's currently realy underappreciated and that it has not received the attention it deserves in the Rust gui world.

Cheers,
Spiros

Stack trace:
```bash
    Finished release [optimized + debuginfo] target(s) in 0.28s
     Running `target\release\makepad.exe`
thread '<unnamed>' panicked at 'Cannot bind server address: Os { code: 10013, kind: PermissionDenied, message: "An attempt was made to access a socket in a way forbidden by its access permissions." }', src\libcore\result.rs:1165:5
stack backtrace:
   0:     0x7ff7c30edde3 - backtrace::backtrace::dbghelp::trace
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\dbghelp.rs:88
   1:     0x7ff7c30edde3 - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   2:     0x7ff7c30edde3 - std::sys_common::backtrace::_print_fmt
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\sys_common\backtrace.rs:77
   3:     0x7ff7c30edde3 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\sys_common\backtrace.rs:61
   4:     0x7ff7c304198b - core::fmt::write
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libcore\fmt\mod.rs:1028
   5:     0x7ff7c30ed017 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\io\mod.rs:1412
   6:     0x7ff7c30ecc90 - std::sys_common::backtrace::_print
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\sys_common\backtrace.rs:65
   7:     0x7ff7c30ecc90 - std::sys_common::backtrace::print
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\sys_common\backtrace.rs:50
   8:     0x7ff7c30ecc90 - std::panicking::default_hook::{{closure}}
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\panicking.rs:188
   9:     0x7ff7c30ec3e2 - std::panicking::default_hook
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\panicking.rs:205
  10:     0x7ff7c30ec3e2 - std::panicking::rust_panic_with_hook
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\panicking.rs:464
  11:     0x7ff7c30f1ff0 - std::panicking::continue_panic_fmt
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\panicking.rs:373
  12:     0x7ff7c30ff239 - std::panicking::rust_begin_panic
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\panicking.rs:302
  13:     0x7ff7c303bcbd - core::panicking::panic_fmt
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libcore\panicking.rs:139
  14:     0x7ff7c304219f - core::result::unwrap_failed
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libcore\result.rs:1165
  15:     0x7ff7c3096f30 - core::result::Result<std::net::tcp::TcpListener, std::io::error::Error>::expect<std::net::tcp::TcpListener,std::io::error::Error>
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libcore\result.rs:960
  16:     0x7ff7c2ff11e6 - hub::httpserver::HttpServer::start_http_server
                               at E:\SugarSyncSTUFF\PROJECTS\RUST\WASM\makepad\makepad\hub\src\httpserver.rs:22
  17:     0x7ff7c2ff11e6 - hub::hubworkspace::HubWorkspace::run<closure-0>
                               at E:\SugarSyncSTUFF\PROJECTS\RUST\WASM\makepad\makepad\hub\src\hubworkspace.rs:42
  18:     0x7ff7c303090f - makepad::workspace_main::main
                               at E:\SugarSyncSTUFF\PROJECTS\RUST\WASM\makepad\workspace\src\main.rs:6
  19:     0x7ff7c3024fbd - makepad::app::{{impl}}::handle_app::{{closure}}
                               at E:\SugarSyncSTUFF\PROJECTS\RUST\WASM\makepad\makepad\src\app.rs:403
  20:     0x7ff7c2ff5331 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,()>
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libstd\sys_common\backtrace.rs:129
  21:     0x7ff7c2ff5af7 - std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,()>
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libstd\thread\mod.rs:469
  22:     0x7ff7c2ff1009 - std::panic::{{impl}}::call_once<(),closure-0>
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libstd\panic.rs:317
  23:     0x7ff7c2ff7ec1 - std::panicking::try::do_call
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libstd\panicking.rs:287
  24:     0x7ff7c2ff7ec1 - panic_abort::__rust_maybe_catch_panic
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libpanic_abort\lib.rs:28
  25:     0x7ff7c2ff7ec1 - std::panicking::try
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libstd\panicking.rs:265
  26:     0x7ff7c2ff7ec1 - std::panic::catch_unwind
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libstd\panic.rs:396
  27:     0x7ff7c2ff7ec1 - std::thread::{{impl}}::spawn_unchecked::{{closure}}
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libstd\thread\mod.rs:468
  28:     0x7ff7c2ff7ec1 - core::ops::function::FnOnce::call_once<closure-0,()>
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\libcore\ops\function.rs:227
  29:     0x7ff7c30fe2be - alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\liballoc\boxed.rs:942
  30:     0x7ff7c30ff717 - alloc::boxed::{{impl}}::call_once
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\src\liballoc\boxed.rs:942
  31:     0x7ff7c30ff717 - std::sys_common::thread::start_thread
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\sys_common\thread.rs:13
  32:     0x7ff7c30ff717 - std::sys::windows::thread::{{impl}}::new::thread_start
                               at /rustc/2477e2493e67527fc282c7239e019f7ebd513a1a\/src\libstd\sys\windows\thread.rs:47
  33:     0x7ffd7d9e7bd4 - BaseThreadInitThunk
  34:     0x7ffd7eaaced1 - RtlUserThreadStart
error: process didn't exit successfully: `target\release\makepad.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

**Comment by SpirosMakris** [comment]
Sorry about this,
my overzealous antivirus probably interfered. Deleted the 'edit_repo', recloned it and then it build & run ok. 
Closing this
